# -*- coding: utf-8 -*-
"""functions_and_lambda_expressions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v_X8kjhwY0c-pkRinGty8tRHIzzfM2K1
"""

def my_function():
 print("with in a function")

my_function()

def calculate_sum(a,b):
 return a+b;

print(calculate_sum(4,5))

def calculate_sum_multiplication(a,b):
 return a+b, a*b

var_sum, var_mult= calculate_sum_multiplication(10,3)

print(var_sum)
print(var_mult)

my_var = lambda x : x+100

print(my_var(10))

my_var= lambda a,b : a+b

print(my_var(10,5))