# -*- coding: utf-8 -*-
"""my_pyspark_program1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pdCI2Of-UeokREUi5qa6czTmqW_ZwJig
"""

!wget https://raw.githubusercontent.com/itshunaid/bigdata/main/retailstore.csv

!ls

! wget https://dlcdn.apache.org/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz

!ls

!tar -xvf spark-3.2.0-bin-hadoop3.2.tgz

!ls

!ls spark-3.2.0-bin-hadoop3.2

!ls /usr/lib/jvm

import os

"""This is a jus a sample comment

"""

os.environ["JAVA_HOME"]= "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"]="/content/spark-3.2.0-bin-hadoop3.2"

!ls /content/spark-3.2.0-bin-hadoop3.2

!pip install findspark

import findspark

findspark.init()

from pyspark.sql import SparkSession

spark= SparkSession.builder.master("local[*]").getOrCreate()

!ls

spark.read.option("header",True).csv("retailstore.csv").show()

spark.createDataFrame([{"Google": "Colab","Spark": "Scala"} ,{"Google": "Dataproc","Spark":"Python"}]).show()