# -*- coding: utf-8 -*-
"""pyspark_bank_marketing_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RnIThJt44RPwOwfnLQsYJKriYRJRv1yk
"""

!wget https://dlcdn.apache.org/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz
!tar -xvf spark-3.2.0-bin-hadoop3.2.tgz
import os
os.environ["JAVA_HOME"]= "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"]="/content/spark-3.2.0-bin-hadoop3.2"
!pip install findspark
import findspark
findspark.init()
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()

!wget https://raw.githubusercontent.com/itshunaid/bigdata/main/bank_prospects.csv

!ls

bankProspectsDF = spark.read.csv("bank_prospects.csv",header=True)

bankProspectsDF.show()

bankProspectsDF1 = bankProspectsDF.filter(bankProspectsDF['country'] != "unknown")

bankProspectsDF1.show()

bankProspectsDF1.printSchema()

from pyspark.sql.types import IntegerType,FloatType

bankProspectsDF2 = bankProspectsDF1.withColumn("age", bankProspectsDF1["age"].cast(IntegerType())).withColumn("salary", bankProspectsDF1["salary"].cast(FloatType()))

bankProspectsDF2.printSchema()

from pyspark.sql.functions import mean

mean_age_val = bankProspectsDF2.select(mean(bankProspectsDF2['age'])).collect()

type(mean_age_val)

mean_age_val

mean_age = mean_age_val[0][0]

mean_age

mean_salary_val = bankProspectsDF2.select(mean(bankProspectsDF2['salary'])).collect()

mean_salary = mean_salary_val[0][0]

mean_salary

bankProspectsDF2.show()

bankbankProspectsDF3 = bankProspectsDF2.na.fill(mean_age,["age"])

bankbankProspectsDF3.show()

bankbankProspectsDF4 = bankbankProspectsDF3.na.fill(mean_salary,["salary"])

bankbankProspectsDF4.show()

bankbankProspectsDF4.printSchema()

bankbankProspectsDF4.write.format("csv").save("bank_prospects_transformed")

!ls

!ls bank_prospects_transformed/

!cat bank_prospects_transformed/part-00000-376a1128-e91a-4f62-b574-f6441337a03a-c000.csv