# -*- coding: utf-8 -*-
"""python_basic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dbXNXP4eN3nibqwSA8SCplOmJKwdTXwV
"""

a=3
b=4

print(a*b)

str1="This is a 'string1"
str2='This is a "string2'

print (str2.upper())

print(str1+str2)

var_list=[1,"abc",3,7.3]


var_list[1]

a=2
b=5
c=3

if a==b:
  print(a)
elif a==c:
  print(c)
else:
  print("no conditions matched")

for i in range(10):
 print(i)

with open ("my_file_1.txt","w") as f:
  f.write("sample content")

!ls

!cat my_file_1.txt

with open ("my_file_1.txt","a") as f:
  f.write("more content")

with open ("my_file_1.txt","w") as f:
  f.write("new content")

!cat my_file_1.txt

with open("my_file_1.txt","r") as f:
 print(f.read())

